pipeline {   //Here pipeline is the root element
    agent {
        label 'AGENT-1'
    }
    environment{
        appVersion = ''
        REGION = "us-east-1" 
        ACC_ID = "583023875867"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('initi') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 00-vpc
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('Plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 00-vpc
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Apply') {
            input {
            message "Should we continue?"
            ok "Yes, we should."
            submitter "alice,bob"
            }
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 00-vpc
                            terraform destroy -auto-approve
                        """
                    }
                }
            }
        }
        // Down stream Job
        stage('Trigger SG') {
            steps {
                script {
                    build job: "10-sg",
                    propagate: false, // even SG fails VPC will not be effected.
                    wait: false // VPC will not wait for SG pipeline completion.
                    }
                }
            }
        }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'I will say Hello success'
        }
        failure { 
            echo 'I will say Hello Failure'
        }
    }
}