pipeline {   //Here pipeline is the root element
    agent {
        label 'AGENT-1'
    }
    environment{
        appVersion = ''
        REGION = "us-east-1" 
        ACC_ID = "583023875867"
        PROJECT = "roboshop"
        COMPONENT = "catalogue"
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('Plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform destroy -auto-approve
                        """
                    }
                }
            }
        }
        stage('Bastion EKS ACM ALB') {
            parallel {
            stage('Trigger Bastion') {
                steps {
                    script {
                        build job: "20-bastion",
                        propagate: false, // even SG fails VPC will not be effected.
                        wait: false // VPC will not wait for SG pipeline completion.
                        }
                    }
                }
            stage('Trigger EKS') {
                steps {
                    script {
                        build job: "80-eks",
                        propagate: false, // even SG fails VPC will not be effected.
                        wait: false // VPC will not wait for SG pipeline completion.
                        }
                    }
                }
            stage('ACM ALB') {
                // Sequential 
                stages {
                    steps {
                        script {
                            build job: "60-acm",
                            propagate: false, // even SG fails VPC will not be effected.
                            wait: false // VPC will not wait for SG pipeline completion.
                            }
                        }
                    }
                }
            }
        }
        stage('Trigger ALB') {
        steps {
            script {
                build job: "70-frontend-alb",
                propagate: false, // even SG fails VPC will not be effected.
                wait: false // VPC will not wait for SG pipeline completion.
                }
            }
        }  
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'I will say Hello success'
        }
        failure { 
            echo 'I will say Hello Failure'
        }
    }
}